version: 2
updates:
- package-ecosystem: npm
  directory: "/Client"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: "dev"
  assignees:
  - Catatomik
- package-ecosystem: npm
  directory: "/Server"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: "dev"
  assignees:
  - Catatomik
