name: bibm

services:
  client:
    container_name: bibm-client
    build:
      context: .
      dockerfile: Dockerfile
      target: client
      args:
        EXTERNAL_API_URL: ${EXTERNAL_API_URL}
        EXTERNAL_API_PATH: ${EXTERNAL_API_PATH}
    ports:
      # Forward to busybox httpd server
      - ${CLIENT_PORT}:8080

  server:
    container_name: bibm-server
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - bibm-api
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: bibm-mongodb
    image: mongo:latest
    networks:
      - mongodb
    user: mongodb:mongodb
    volumes:
      # Permissions have to be 777 in order for rootless docker/podman to bind-mount folder
      - ./data/mongodb:/data/db
    command: --quiet --logpath /dev/null

  redis:
    container_name: bibm-redis
    image: redis:alpine
    networks:
      - redis
    volumes:
      - ./data/redis:/data
    environment:
      REDIS_ARGS: "--save 60 1 --loglevel warning"

networks:
  # "Shared" network for BIBM API
  bibm-api:
    name: bibm-api
  # "Shared" network for BIBM mongodb source data
  mongodb:
    name: bibm-mongodb
  # Private network for redis
  redis:
