# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - "Client/*"
      - "Server/*"
      - "Data/*"
      - ".github/workflows/*"
  pull_request:
    branches: [main, dev]
    paths:
      - "Client/*"
      - "Server/*"
      - "Data/*"
      - ".github/workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      # Globally install
      - run: pnpm --config.dedupe-peer-dependents=false install

      - name: Build Common
        run: cd Common/ && pnpm run --if-present build

      - name: Build Data
        run: cd Data/ && pnpm run --if-present build

      - name: Build Compute
        run: cd Compute/ && pnpm run --if-present build

      - name: Build Server
        run: cd Server/ && pnpm run --if-present build

      - name: Build Client
        run: cd Client/ && pnpm run --if-present build
