# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'Client/*'
      - 'Server/*'
      - '.github/workflows/*'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Client/*'
      - 'Server/*'
      - '.github/workflows/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    # Build Server to build Client
    - run: cd Server/ && pnpm install
    - run: cd Server/ && pnpm run bundle:client --if-present
    - run: cd Client/ && pnpm add file:../Server/public/server-1.0.0.tgz
    - run: cd Client/ && pnpm run build --if-present
    
