# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - "Common/*"
      - "Data/*"
      - "Compute/*"
      - "Server/*"
      - "Client/*"
      - ".github/workflows/*"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  pull_request:
    branches: [main, dev]
    paths:
      - "Common/*"
      - "Data/*"
      - "Compute/*"
      - "Server/*"
      - "Client/*"
      - ".github/workflows/*"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install Common
        run: pnpm -F "common" install

      - name: Build Common
        run: cd Common/ && pnpm run build

      - name: Install Data
        run: pnpm -F "data" install

      - name: Build Data
        run: cd Data/ && pnpm run build

      - name: Install Compute
        run: pnpm -F "compute" install

      # Will fail for the 1st time, but still emit required files to continue building
      - name: Build Compute

        run: cd Compute/ && pnpm run build || true

      - name: Install Server
        run: pnpm -F "server" install

      - name: Build Server
        run: cd Server/ && pnpm run compile

      - name: Build Compute (2)
        run: cd Compute/ && pnpm run build

      - name: Install Client
        run: pnpm -F "client" install

      - name: Build Client
        run: cd Client/ && pnpm run build
