# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - "Client/*"
      - "Server/*"
      - "Data/*"
      - ".github/workflows/*"
  pull_request:
    branches: [main, dev]
    paths:
      - "Client/*"
      - "Server/*"
      - "Data/*"
      - ".github/workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      # Build Common to build Data to build Server to build Client
      - run: pnpm -F "common" --config.dedupe-peer-dependents=false install

      - run: pnpm -F "data" --config.dedupe-peer-dependents=false install

      - run: pnpm -F "compute" --config.dedupe-peer-dependents=false install
      - run: cd Compute/ && pnpm run --if-present build

      - run: pnpm -F "server" --config.dedupe-peer-dependents=false install
      - run: cd Server/ && pnpm run --if-present build

      - run: pnpm -F "client" --config.dedupe-peer-dependents=false install
      - run: cd Client/ && pnpm run --if-present build
